name: make snippet JSON

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1
    
    - run: mkdir output

    - name: Make JSON
      run: python3 build_snippet.py > output/cpp.json

    - name: Upload json
      uses: actions/upload-artifact@master
      with:
        name: output
        path: output
